# Generated by Django 3.2.16 on 2023-01-19 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_comments_converstations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_starter', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='forum.rooms')),
            ],
            options={
                'verbose_name_plural': 'Converstaions',
            },
        ),
        migrations.RemoveField(
            model_name='comments',
            name='converstaion',
        ),
        migrations.DeleteModel(
            name='Converstations',
        ),
        migrations.AddField(
            model_name='comments',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_comments', to='forum.conversations'),
            preserve_default=False,
        ),
    ]
