# Generated by Django 3.2.16 on 2023-01-19 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_remove_comments_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='conversation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_comments', to='forum.conversations'),
        ),
    ]
