# Generated by Django 3.2.16 on 2023-01-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20230119_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
