# Generated by Django 3.2.16 on 2023-01-20 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_comments_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='tags',
        ),
        migrations.AddField(
            model_name='rooms',
            name='tags',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='room_tags', to='forum.tags'),
        ),
    ]
