# Generated by Django 3.2.16 on 2023-02-22 11:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_rename_conversation_slug_conversations_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
